// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTZcx9FfeKx9P80QiMcnQxBB-LQG61ow',
    appId: '1:413544048135:web:f517be4ccd8b5ceaa7aca2',
    messagingSenderId: '413544048135',
    projectId: 'acheev-89f7b',
    authDomain: 'acheev-89f7b.firebaseapp.com',
    storageBucket: 'acheev-89f7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxoapCOjdW6HxMJF-WJJk0mD2HslTvuiM',
    appId: '1:413544048135:android:875db9fc11b2a3b6a7aca2',
    messagingSenderId: '413544048135',
    projectId: 'acheev-89f7b',
    storageBucket: 'acheev-89f7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYwVt-LTniHyTSmnkHvi8SHabUach_Juc',
    appId: '1:413544048135:ios:54153d4bf70a3435a7aca2',
    messagingSenderId: '413544048135',
    projectId: 'acheev-89f7b',
    storageBucket: 'acheev-89f7b.appspot.com',
    iosClientId: '413544048135-35neljatf9gua776reejvre4aapbo116.apps.googleusercontent.com',
    iosBundleId: 'com.example.acheev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYwVt-LTniHyTSmnkHvi8SHabUach_Juc',
    appId: '1:413544048135:ios:54153d4bf70a3435a7aca2',
    messagingSenderId: '413544048135',
    projectId: 'acheev-89f7b',
    storageBucket: 'acheev-89f7b.appspot.com',
    iosClientId: '413544048135-35neljatf9gua776reejvre4aapbo116.apps.googleusercontent.com',
    iosBundleId: 'com.example.acheev',
  );
}
